// @ts-check

/**
 * One autogenerated sidebar, shared by both docs-plugin instances (guide and
 * concept). Autogeneration is per-instance — each plugin only ever sees its
 * own subtree (../docs/guide or ../docs/concept) — so a single generic
 * "autogenerated from the root" config is correct for both without further
 * instance-specific tuning this slice.
 *
 * @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
  tutorialSidebar: [
    {
      type: 'autogenerated',
      dirName: '.',
    },
  ],
};

module.exports = sidebars;
