// @ts-check

/**
 * The concept pages are short enough for their front-matter order to remain
 * useful. The guide uses sidebars-guide.js because it needs reader-goal groups.
 *
 * @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
  tutorialSidebar: [
    {
      type: 'autogenerated',
      dirName: '.',
    },
  ],
};

module.exports = sidebars;
